CREATE TABLE people (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, kana TEXT NOT NULL);
CREATE TABLE person_map (id INTEGER PRIMARY KEY AUTOINCREMENT, story_id INTEGER NOT NULL, person_id INTEGER NOT NULL);
CREATE TABLE stories (id INTEGER PRIMARY KEY AUTOINCREMENT, number INTEGER, title TEXT NOT NULL);
